token: f3bb132601264e40bfbc22cfb8419295

vendors:
  vendors:
  PT ANUGERAH BERSATU:
    - plate: B9588FEV
      type: TRONTON

    - plate: B9304PXS
      type: FUSO

    - plate: B9823UEX
      type: TRONTON

    - plate: B9909SEU
      type: TRONTON

    - plate: B9687SEU
      type: TRONTON

    - plate: B9326UEX
      type: TRONTON

    - plate: A9498PB
      type: TRONTON

    - plate: B9605FXX
      type: FUSO

    - plate: K9897OB
      type: TRONTON

    - plate: K8316ZK
      type: FUSO

    - plate: K8223OK
      type: TRONTON

    - plate: B9913UXT
      type: FUSO

    - plate: B9600SEU
      type: TRONTON

    - plate: B9284KXW
      type: CDDL
    
    - plate: B9526KXV
      type: CDDL

    - plate: B9897SEU
      type: TRONTON

    - plate: B9908SEU
      type: TRONTON

    - plate: B9748UXV
      type: FUSO

    - plate: H8301KX
      type: FUSO

    - plate: K8220OK
      type: FUSO

  PT. SERIKAT HANTAR EKSPEDISI:
    - plate: A9040UI
      type: TRONTON

    - plate: A9040UI
      type: TRONTON

    - plate: A8094HL
      type: CDDL

    - plate: B9059SEU
      type: TRONTON
    
    - plate: B9257SYN
      type: TRONTON

    - plate: B9081WX
      type: TRONTON

    - plate: B9834FYV
      type: TRONTON

    - plate: B9479UXZ
      type: CDDL

    - plate: B9704BXU
      type: FUSO

    - plate: B9876FFX
      type: FUSO

    - plate: B9876FFX
      type: FUSO

    - plate: B9704BXU
      type: FUSO
    
    - plate: B9439CXT
      type: CDDL

  PT. ASIA PASIFIK LOGISTIK:
    - plate: B9883PXT
      type: FUSO